"use client";
import { useMemo, useState } from "react";

const automations = [
  { title:"Lead capture to CRM", desc:"Qualify form leads, enrich the record, and alert sales instantly.", tools:["Webhooks","OpenAI","Sheets","Slack"], level:"Starter", time:"18 min", type:"Sales" },
  { title:"AI inbox triage", desc:"Classify incoming email and route replies to the right workflow.", tools:["Gmail","OpenAI","Notion"], level:"Popular", time:"24 min", type:"Operations" },
  { title:"Meeting follow-up engine", desc:"Turn call notes into tasks, summaries, and client follow-ups.", tools:["Zoom","OpenAI","Asana"], level:"Starter", time:"16 min", type:"Operations" },
  { title:"Content repurposing studio", desc:"Transform one long-form idea into a week of social content.", tools:["OpenAI","Drive","Buffer"], level:"Pro", time:"28 min", type:"Marketing" },
  { title:"Customer feedback radar", desc:"Collect, score, and surface feedback themes automatically.", tools:["Typeform","OpenAI","Slack"], level:"Pro", time:"22 min", type:"Operations" },
  { title:"Invoice chase assistant", desc:"Track overdue invoices and send thoughtful reminders on time.", tools:["Stripe","Gmail","Sheets"], level:"Popular", time:"20 min", type:"Sales" },
];
const filters=["All","Sales","Operations","Marketing"];
const faqs=[
  ["Do I need to know how to code?","No. The blueprints use visual automation tools and each download includes a clear setup guide. Basic comfort with web apps is enough."],
  ["Are the templates safe to use?","Yes. Every blueprint passes a privacy scrub before upload, so private connection IDs, API keys, emails, and live webhooks are replaced with obvious placeholders."],
  ["Which automation platform do I need?","The current library is focused on Make.com. Members can vote on future Make, n8n, and Zapier releases."],
  ["What happens if I get stuck?","Use the setup guide, join a practical workshop, or submit a request through the member portal."],
];

export default function Home(){
 const [filter,setFilter]=useState("All"); const [openFaq,setOpenFaq]=useState<number|null>(0);
 const visible=useMemo(()=>filter==="All"?automations:automations.filter(a=>a.type===filter),[filter]);
 return <main>
  <nav className="nav shell" aria-label="Main navigation"><a className="brand" href="#top"><span className="brandMark">A</span><span>Automate<span className="lime">Lab</span></span></a><div className="navLinks"><a href="#library">Library</a><a href="#workshop">Course</a><a href="#membership">Membership</a><a href="/account">My access</a></div><a className="navCta" href="/account">Sign in / My access <span>↗</span></a></nav>
  <section className="hero shell" id="top"><div className="eyebrow"><span className="pulse"/> New templates added every month</div><h1>Stop watching AI.<br/><span>Start building with it.</span></h1><p className="heroCopy">Production-ready Make.com automation blueprints, a practical live course, and clear setup guides—built for people who want working systems, not more theory.</p><div className="heroActions"><a className="button primary" href="/library">Get 100 automations <span>→</span></a><a className="button textButton" href="#how">See how it works <span className="play">▶</span></a></div><div className="socialProof"><div className="avatars"><i>GM</i><i>AJ</i><i>SK</i><i>+</i></div><div><strong>Built for doers</strong><span>Import. Connect. Launch.</span></div></div>
   <div className="workflow"><div className="windowTop"><div className="dots"><i/><i/><i/></div><span>lead-capture-to-crm.blueprint</span><div className="status"><i/> Ready to import</div></div><div className="canvas">{[["W","TRIGGER","New lead","Webhook received","purple"],["✦","INTELLIGENCE","Qualify lead","Score & enrich with AI","green"],["S","ACTION","Update CRM","Create contact + deal","blue"],["#","NOTIFY","Alert sales","Send to Slack","pink"]].map((n,i)=><div className="flowItem" key={n[2]}><div className={`node ${i===1?"featured":""}`}><b className={`icon ${n[4]}`}>{n[0]}</b><small>{n[1]}</small><strong>{n[2]}</strong><span>{n[3]}</span></div>{i<3&&<div className="connector"><i>✓</i></div>}</div>)}</div><div className="runBar"><span><i/> Last run: 2 minutes ago</span><b>42 operations saved this week</b></div></div>
  </section>
  <section className="problem"><div className="shell problemGrid"><div><p className="kicker">The gap isn&apos;t access. It&apos;s execution.</p><h2>You don&apos;t need another<br/>10-hour tutorial.</h2></div><div><p>You need a proven starting point, safe files, and instructions that make sense the first time.</p><ul><li><span>01</span>Every blueprint is scrubbed of private data</li><li><span>02</span>Every app connection is listed up front</li><li><span>03</span>Every setup guide is written for real implementation</li></ul></div></div></section>
  <section className="library shell" id="library"><div className="sectionHead"><div><p className="kicker dark">Explore the library</p><h2>Automations that earn<br/>their place in your stack.</h2></div><p>Start with the problem you want to solve. Each blueprint shows the tools required and the time to launch.</p></div><div className="filterRow">{filters.map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="cardGrid">{visible.map((item,i)=><article className="card" key={item.title}><div className="cardTop"><span className={`tag t${i%3}`}>{item.level}</span><span className="arrow">↗</span></div><h3>{item.title}</h3><p>{item.desc}</p><div className="tools">{item.tools.map(t=><span key={t}>{t}</span>)}</div><footer><span>◷ {item.time} setup</span><a href="/library"><b>Get access →</b></a></footer></article>)}</div><div className="libraryCta"><p><strong>100</strong><span>ready-to-import<br/>automation blueprints</span></p><a className="button darkButton" href="/library">See the complete library →</a></div></section>
  <section className="how" id="how"><div className="shell"><p className="kicker">From download to done</p><h2>Three steps. No guesswork.</h2><div className="steps">{[["01","↓","Choose & download","Pick a workflow for your goal. See every connector before you commit."],["02","⌁","Connect your tools","Follow the plain-English guide to add your accounts and placeholders."],["03","▶","Test & launch","Run the checklist, switch it on, and reclaim the hours."]].map(s=><article key={s[0]}><span>{s[0]}</span><div className="stepIcon">{s[1]}</div><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></div></section>
  <section className="workshop shell" id="workshop"><div className="workshopCard"><div className="workshopCopy"><p className="kicker dark">Live build course</p><h2>Build your first AI<br/>workflow with us.</h2><p>A focused, hands-on session on a date you select. Arrive with an idea; leave with a working automation and the confidence to build the next one.</p><div className="workshopMeta"><span><b>3 hours</b>live & practical</span><span><b>Small group</b>real support</span><span><b>Scheduled dates</b>choose your session</span></div><a className="button primary" href="/course">View course dates →</a></div><div className="terminalCard"><div className="terminalHeader"><span>COURSE OUTPUT</span><i>LIVE</i></div><div className="terminalLines">{["Map the process","Build the scenario","Add AI intelligence","Test edge cases","Ship it"].map((x,i)=><p key={x}><b>0{i+1}</b><span>{x}</span><i>{i===4?"ready":"done"}</i></p>)}</div></div></div></section>
  <section className="membership" id="membership"><div className="shell membershipGrid"><div><p className="kicker">The automation library</p><h2>One membership.<br/>A growing operating system.</h2><p className="membershipText">Get all 100 blueprints today and every new release published while your subscription remains active.</p><div className="membershipList"><span>✓ All 100 Make.com blueprints</span><span>✓ Step-by-step setup docs</span><span>✓ Continuous new releases</span><span>✓ Private customer download portal</span></div></div><div className="priceCard"><div className="priceTop"><span>BLUEPRINT MEMBERSHIP</span><b>Growing library</b></div><div className="price"><sup>R</sup><strong>179</strong><span>/month</span></div><p>Cancel anytime. Files already downloaded remain yours.</p><a className="button primary full" href="/library">Subscribe securely →</a><small>Secure card checkout · Access after verified payment</small><div className="starter"><span>Looking for the live course?</span><a href="/course"><b>Live course · Choose a date →</b></a></div></div></div></section>
  <section className="faq shell"><div><p className="kicker dark">Questions, answered</p><h2>Before you<br/>start building.</h2></div><div className="accordions">{faqs.map((faq,i)=><article key={faq[0]}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}><span>{faq[0]}</span><b>{openFaq===i?"−":"+"}</b></button>{openFaq===i&&<p>{faq[1]}</p>}</article>)}</div></section>
  <footer className="footer"><div className="shell"><div className="footerLead"><div><a className="brand inverse" href="#top"><span className="brandMark">A</span><span>Automate<span className="lime">Lab</span></span></a><h2>Make your work<br/>work for you.</h2></div><a className="button primary" href="#membership">Explore the library →</a></div><div className="footerBottom"><span>© 2026 AutomateLab</span><div><a href="#library">Library</a><a href="#workshop">Workshops</a><a href="/contact">Contact us</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><span>Built for people who build.</span></div></div></footer>
 </main>
}
